import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";
import {Roboto_Mono} from 'next/font/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Loja de Periféricos Genérica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${robotoMono.variable} antialiased  bg-neutral-100 font-main overflow-x-hidden `}
      >

        <div className="mb-26">
          <Navbar />
        </div>
        <Banner />
        <div className=" flex  items-start justify-center min-h-screen   ">
          {children}
        </div>
        <div>
        <Footer />
        </div>
      </body>
    </html>
  );
}
